package dev.herakles.nightjar.modules.fireflyjar

import kotlinx.coroutines.flow.Flow

/**
 * Makes a firefly's row and its attached media file inseparable (gate-20, INV-6). Every deletion
 * path that used to touch [FireflyDao] directly now goes through here so a firefly can never be
 * "deleted" in one store while surviving in the other.
 *
 * Stage A rewired the shelf's clear-history path. Stage B (gate-17) added the shared
 * write-then-insert path ([insertWithMedia] / [insert]). The three catch sites (ImageStegoScreen,
 * AudioStegoScreen, AcousticModemScreen) still write through [FireflyDao] directly and move to
 * this repository in a later stage.
 *
 * Stage C (this task, gate-20) makes file deletion reference-counted via
 * [deleteMediaFileIfUnreferenced]. Today [FireflyMediaStore.write] names every file with a random
 * UUID, so exactly one row ever references a given `mediaPath` and an unconditional delete is
 * safe. Task #24 switches that filename to a content hash, at which point two fireflies with
 * byte-identical carriers share one file -- an unconditional delete would then destroy a live
 * firefly's carrier out from under it while "deleting" or "rolling back" an unrelated one. This
 * stage is a no-op today (the count is always 0) and load-bearing the moment #24 lands.
 */
class FireflyRepository(
    private val dao: FireflyDao,
    private val mediaStore: FireflyMediaStore,
) {

    /**
     * Writes [media] to disk first, then inserts [record] carrying the returned filename in
     * `mediaPath` and `media.size` in `mediaBytes`. `record.carrierKind` is used as-is -- the
     * caller decides "IMAGE" vs "AUDIO"; this function never infers it from [extension].
     *
     * Write-then-insert, not insert-then-update: [FireflyMediaStore.write] generates the filename
     * before any row exists, so the one and only [dao] insert can carry that filename immediately.
     * Insert-then-update would need a second round-trip to backfill the filename once Room hands
     * back the autogenerated id -- write-then-insert skips that trip entirely.
     *
     * Truncated-write decision (Stage A review, gate-17): chose (b) -- document that the orphan
     * sweep is sufficient -- over (a) temp-name-then-rename. The reviewer's real worry was a row
     * landing with a truncated file attached (a reader would treat it as valid media, which is
     * strictly worse than an ordinary orphan). But that combination cannot occur under this
     * control flow: [filename] only exists as a local value, and only reaches [dao].insert, AFTER
     * `mediaStore.write` has already returned. If the process dies mid-`writeBytes`, execution
     * never leaves the `write` call, so `insertWithMedia` never reaches the insert -- the
     * truncated file is left with zero rows referencing it, i.e. an ordinary orphan that
     * [sweepOrphans] reclaims on next launch. A row can only ever be inserted with a filename
     * that finished writing. Given that, temp-then-rename would guard against a case this
     * ordering already rules out by construction, at the cost of an extra rename op (itself a
     * second place a mid-op crash could occur) -- not worth the complexity here.
     *
     * If [dao].insert throws, the just-written file is deleted before rethrowing -- UNLESS another
     * row already references that filename (post-#24 dedup: [mediaStore].write can hand back an
     * EXISTING filename another row already owns), in which case deleting it would destroy that
     * row's live carrier while "cleaning up" this failed insert. Otherwise every failed insert
     * leaves an orphan that only the next-launch sweep can reclaim.
     */
    suspend fun insertWithMedia(record: FireflyRecord, media: ByteArray, extension: String) {
        val filename = mediaStore.write(media, extension)
        try {
            dao.insert(record.copy(mediaPath = filename, mediaBytes = media.size.toLong()))
        } catch (e: Exception) {
            // The insert failed, so there is no row -- and therefore no id -- to exclude. Pass
            // UNASSIGNED_ID, a sentinel no real row can ever have, so every existing row that
            // names [filename] correctly counts as "other" and blocks the delete.
            deleteMediaFileIfUnreferenced(filename, excludingId = UNASSIGNED_ID)
            throw e
        }
    }

    /** Passthrough insert for media-less fireflies -- no file touched, `mediaPath`/`mediaBytes` are whatever [record] already carries (null/0 for an un-attached catch). */
    suspend fun insert(record: FireflyRecord) {
        dao.insert(record)
    }

    fun observeByModule(moduleId: String): Flow<List<FireflyRecord>> = dao.observeByModule(moduleId)

    fun observeAll(): Flow<List<FireflyRecord>> = dao.observeAll()

    fun observeTotalMediaBytes(): Flow<Long?> = dao.observeTotalMediaBytes()

    /**
     * Reads a persisted carrier's raw bytes back off disk, by [FireflyRecord.mediaPath].
     * Delegates straight to [FireflyMediaStore.read] -- the carrier viewer's
     * (`JarDetailScreen.kt`'s `FireflyCarrierBlock`) one read path into media this repository
     * already owns writing and deleting. Returns null if the file is missing (deleted, evicted,
     * or a pre-migration record that was never given media in the first place).
     *
     * Does not self-dispatch, same as [insertWithMedia]'s own unwrapped [mediaStore] calls --
     * callers already invoke this from a background dispatcher (see the carrier viewer's
     * `withContext(Dispatchers.IO)`).
     */
    suspend fun readMedia(path: String): ByteArray? = mediaStore.read(path)

    /**
     * Deletes every firefly: all attached media files, then all rows.
     *
     * Files before rows, deliberately. If the process dies mid-way, the surviving state is rows
     * pointing at missing files -- the UI already tolerates that (a media-less record renders
     * text-only). The reverse order would leave files no row can ever name again: unreclaimable
     * except by [sweepOrphans], which needs a live row set to sweep against in the first place.
     */
    suspend fun clearAll() {
        mediaStore.deleteAll()
        dao.clearAll()
    }

    /**
     * Deletes one firefly by [id]: its attached media file (if any), then its row.
     *
     * Same file-before-row ordering and reasoning as [clearAll]. A pre-migration record (or any
     * record never given media) has a null `mediaPath` -- that's not an error, just nothing to
     * delete on disk before the row goes. The file is only deleted if no OTHER row still
     * references it -- see [deleteMediaFileIfUnreferenced].
     */
    suspend fun deleteFirefly(id: Long) {
        val record = dao.getById(id)
        // [id]'s own row still exists in the table at this point (it's deleted below), so it must
        // be excluded -- otherwise a single-reference file would always see a count of >= 1 (itself)
        // and never be deleted.
        record?.mediaPath?.let { deleteMediaFileIfUnreferenced(it, excludingId = id) }
        dao.deleteById(id)
    }

    /** Reclaims media files on disk with no row referencing them (crash-recovery sweep, INV-6). */
    suspend fun sweepOrphans() {
        mediaStore.sweepOrphans(dao.allMediaPaths().toSet())
    }

    /**
     * Deletes the media file at [path] only if no OTHER row (i.e. not [excludingId]) still
     * references it.
     *
     * The single point [deleteFirefly] and the [insertWithMedia] rollback path route through --
     * deliberately, so the two callers cannot drift into different reference-check logic. Today
     * ([FireflyMediaStore.write] names files by random UUID) the count this checks is always 0,
     * making this a no-op wrapper around an unconditional delete. It becomes load-bearing the
     * moment task #24 lands content-addressed filenames and two rows can share one file: deleting
     * unconditionally at that point would silently destroy another firefly's carrier.
     */
    private suspend fun deleteMediaFileIfUnreferenced(path: String, excludingId: Long) {
        if (dao.countReferencesTo(path, excludingId) == 0) {
            mediaStore.delete(path)
        }
    }

    private companion object {
        /**
         * Sentinel passed as `excludingId` when there is no row to exclude -- the
         * [insertWithMedia] rollback path, where the insert failed and no row was ever created.
         * `0L` matches [FireflyRecord.id]'s own "not yet inserted" default, and Room's
         * `autoGenerate = true` primary keys start at 1, so no real row can ever hold this value.
         */
        const val UNASSIGNED_ID = 0L
    }
}
