package dev.herakles.nightjar.modules.fireflyjar

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.withContext

/**
 * Makes a firefly's row and its attached media file inseparable (gate-20, INV-6). Every deletion
 * path that used to touch [FireflyDao] directly now goes through here so a firefly can never be
 * "deleted" in one store while surviving in the other.
 *
 * Stage A rewired the shelf's clear-history path. Stage B (gate-17) added the shared
 * write-then-insert path ([insertWithMedia] / [insert]). The three catch sites (ImageStegoScreen,
 * AudioStegoScreen, AcousticModemScreen) still write through [FireflyDao] directly and move to
 * this repository in a later stage.
 *
 * Stage C (gate-20) made file deletion reference-counted via [deleteMediaFileIfUnreferenced].
 * [FireflyMediaStore.write] names every file by content hash (SHA-256), so two fireflies with
 * byte-identical carriers collapse onto one file -- an unconditional delete would destroy a live
 * firefly's carrier out from under it while "deleting" or "rolling back" an unrelated one. This is
 * load-bearing today, exercised end-to-end in [FireflyRepositoryTest]'s dedup + reference-counting
 * coverage.
 *
 * Every file-I/O path here ([clearAll], [deleteFirefly], [deleteMediaFileIfUnreferenced],
 * [insertWithMedia]'s write/rollback) runs under [Dispatchers.IO] -- fixed after a review found
 * the shelf's "clear history" launching [clearAll] on whatever dispatcher the caller happened to
 * be on (the composition/Main dispatcher for a plain `rememberCoroutineScope().launch { }`),
 * which blocked the UI thread for the full duration of a multi-file delete loop.
 */
class FireflyRepository(
    private val dao: FireflyDao,
    private val mediaStore: FireflyMediaStore,
) {

    /**
     * Writes [media] to disk first, then inserts [record] carrying the returned filename in
     * `mediaPath` and `media.size` in `mediaBytes`. `record.carrierKind` is used as-is -- the
     * caller decides "IMAGE" vs "AUDIO"; this function never infers it from [extension].
     *
     * Write-then-insert, not insert-then-update: [FireflyMediaStore.write] generates the filename
     * before any row exists, so the one and only [dao] insert can carry that filename immediately.
     * Insert-then-update would need a second round-trip to backfill the filename once Room hands
     * back the autogenerated id -- write-then-insert skips that trip entirely.
     *
     * Truncated-write decision (Stage A review, gate-17): chose (b) -- document that the orphan
     * sweep is sufficient -- over (a) temp-name-then-rename. The reviewer's real worry was a row
     * landing with a truncated file attached (a reader would treat it as valid media, which is
     * strictly worse than an ordinary orphan). But that combination cannot occur under this
     * control flow: [filename] only exists as a local value, and only reaches [dao].insert, AFTER
     * `mediaStore.write` has already returned. If the process dies mid-`writeBytes`, execution
     * never leaves the `write` call, so `insertWithMedia` never reaches the insert -- the
     * truncated file is left with zero rows referencing it, i.e. an ordinary orphan that
     * [sweepOrphans] reclaims on next launch. A row can only ever be inserted with a filename
     * that finished writing. Given that, temp-then-rename would guard against a case this
     * ordering already rules out by construction, at the cost of an extra rename op (itself a
     * second place a mid-op crash could occur) -- not worth the complexity here.
     *
     * If [dao].insert throws, the just-written file is deleted before rethrowing -- UNLESS another
     * row already references that filename (post-#24 dedup: [mediaStore].write can hand back an
     * EXISTING filename another row already owns), in which case deleting it would destroy that
     * row's live carrier while "cleaning up" this failed insert. Otherwise every failed insert
     * leaves an orphan that only the next-launch sweep can reclaim.
     *
     * Returns the inserted row's id (W2-3, gate-36: a practice catch needs it immediately to mark
     * itself via [dev.herakles.nightjar.trail.TrailStateStore.markPractice]) -- a thin passthrough
     * of [FireflyDao.insert]'s own return value.
     */
    suspend fun insertWithMedia(record: FireflyRecord, media: ByteArray, extension: String): Long {
        return withContext(Dispatchers.IO) {
            val filename = mediaStore.write(media, extension)
            try {
                dao.insert(record.copy(mediaPath = filename, mediaBytes = media.size.toLong()))
            } catch (e: Exception) {
                // The insert failed, so there is no row -- and therefore no id -- to exclude. Pass
                // UNASSIGNED_ID, a sentinel no real row can ever have, so every existing row that
                // names [filename] correctly counts as "other" and blocks the delete.
                deleteMediaFileIfUnreferenced(filename, excludingId = UNASSIGNED_ID)
                throw e
            }
        }
    }

    /** Passthrough insert for media-less fireflies -- no file touched, `mediaPath`/`mediaBytes`
     *  are whatever [record] already carries (null/0 for an un-attached catch). Returns the
     *  inserted row's id, same reasoning as [insertWithMedia]'s own return value. */
    suspend fun insert(record: FireflyRecord): Long = dao.insert(record)

    fun observeByModule(moduleId: String): Flow<List<FireflyRecord>> = dao.observeByModule(moduleId)

    fun observeAll(): Flow<List<FireflyRecord>> = dao.observeAll()

    fun observeTotalMediaBytes(): Flow<Long> = dao.observeTotalMediaBytes()

    /**
     * Reads a persisted carrier's raw bytes back off disk, by [FireflyRecord.mediaPath].
     * Delegates straight to [FireflyMediaStore.read] -- the carrier viewer's
     * (`JarDetailScreen.kt`'s `FireflyCarrierBlock`) one read path into media this repository
     * already owns writing and deleting. Returns null if the file is missing (deleted, evicted,
     * or a pre-migration record that was never given media in the first place).
     *
     * Does not self-dispatch, same as [insertWithMedia]'s own unwrapped [mediaStore] calls --
     * callers already invoke this from a background dispatcher (see the carrier viewer's
     * `withContext(Dispatchers.IO)`).
     */
    suspend fun readMedia(path: String): ByteArray? = mediaStore.read(path)

    /**
     * Deletes every firefly: all attached media files, then all rows.
     *
     * Files before rows, deliberately. If the process dies mid-way, the surviving state is rows
     * pointing at missing files -- the UI already tolerates that (a media-less record renders
     * text-only). The reverse order would leave files no row can ever name again: unreclaimable
     * except by [sweepOrphans], which needs a live row set to sweep against in the first place.
     */
    suspend fun clearAll() {
        withContext(Dispatchers.IO) {
            mediaStore.deleteAll()
            dao.clearAll()
        }
    }

    /**
     * Deletes one firefly by [id]: its attached media file (if any), then its row.
     *
     * Same file-before-row ordering and reasoning as [clearAll]. A pre-migration record (or any
     * record never given media) has a null `mediaPath` -- that's not an error, just nothing to
     * delete on disk before the row goes. The file is only deleted if no OTHER row still
     * references it -- see [deleteMediaFileIfUnreferenced].
     */
    suspend fun deleteFirefly(id: Long) {
        withContext(Dispatchers.IO) {
            val record = dao.getById(id)
            // [id]'s own row still exists in the table at this point (it's deleted below), so it
            // must be excluded -- otherwise a single-reference file would always see a count of
            // >= 1 (itself) and never be deleted.
            record?.mediaPath?.let { deleteMediaFileIfUnreferenced(it, excludingId = id) }
            dao.deleteById(id)
        }
    }

    /** Reclaims media files on disk with no row referencing them (crash-recovery sweep, INV-6). */
    suspend fun sweepOrphans() {
        withContext(Dispatchers.IO) {
            mediaStore.sweepOrphans(dao.allMediaPaths().toSet())
        }
    }

    /**
     * One-shot snapshot of stored-media state for [dev.herakles.nightjar.DebugProbe]'s
     * `stored_media` report (gate-20 v4 probe contract, spec.md's Runtime Verification Surface):
     * how many fireflies exist, how many carry an attached media file, how many bytes that media
     * occupies on disk (deduplicated -- [observeTotalMediaBytes]'s own KDoc), and how many files
     * on disk no row currently references. Gathers all four under [Dispatchers.IO], the same
     * dispatcher [sweepOrphans] uses for its own directory listing.
     *
     * [StoredMediaSnapshot.orphanFileCount] comes from [FireflyMediaStore.countUnreferenced],
     * which counts EVERY unreferenced file, not only the ones [sweepOrphans] would reclaim if run
     * at that instant -- see [FireflyMediaStore.countUnreferenced]'s own KDoc for why that's the
     * deliberate choice (a probe snapshot taken inside the write-then-insert gap can therefore
     * read one higher than the sweep would actually reclaim right then; that's a real, possible
     * value, not a bug).
     */
    suspend fun probeSnapshot(): StoredMediaSnapshot = withContext(Dispatchers.IO) {
        val knownPaths = dao.allMediaPaths().toSet()
        StoredMediaSnapshot(
            recordCount = dao.countAll(),
            recordsWithMediaCount = dao.countWithMedia(),
            totalMediaBytes = dao.observeTotalMediaBytes().first(),
            orphanFileCount = mediaStore.countUnreferenced(knownPaths),
        )
    }

    /**
     * Deletes the media file at [path] only if no OTHER row (i.e. not [excludingId]) still
     * references it.
     *
     * The single point [deleteFirefly] and the [insertWithMedia] rollback path route through --
     * deliberately, so the two callers cannot drift into different reference-check logic.
     * [FireflyMediaStore.write] names files by content hash, so two rows can genuinely share one
     * file today: deleting unconditionally here would silently destroy another firefly's carrier
     * the moment that happens, which is exactly what [FireflyRepositoryTest]'s dedup +
     * reference-counting tests exercise end to end.
     */
    private suspend fun deleteMediaFileIfUnreferenced(path: String, excludingId: Long) {
        if (dao.countReferencesTo(path, excludingId) == 0) {
            mediaStore.delete(path)
        }
    }

    private companion object {
        /**
         * Sentinel passed as `excludingId` when there is no row to exclude -- the
         * [insertWithMedia] rollback path, where the insert failed and no row was ever created.
         * `0L` matches [FireflyRecord.id]'s own "not yet inserted" default, and Room's
         * `autoGenerate = true` primary keys start at 1, so no real row can ever hold this value.
         */
        const val UNASSIGNED_ID = 0L
    }
}

/** [FireflyRepository.probeSnapshot]'s result -- see that function's KDoc for what each field
 *  means and how it's computed. */
data class StoredMediaSnapshot(
    val recordCount: Int,
    val recordsWithMediaCount: Int,
    val totalMediaBytes: Long,
    val orphanFileCount: Int,
)
